[project]
name = "GNCE"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
  "pyrdf2vec==0.2.3",
  "rdflib",
  "cachetools",
  "easydict>=1.13",
  "gensim>=4.3.0,<4.4.0",
  "matplotlib>=3.10.5",
  "nest_asyncio",
  "ninja>=1.13.0",
  "scikit-learn>=1.7.1",
  "scipy>=1.9.0,<1.12.0",
  "torch>=1.12.0,<2.0.0",
  "torch-geometric",
  "torch-scatter",
]

[tool.uv.extra-build-dependencies]
torch-scatter = ["torch"]

[tool.uv.sources.torch]
index = "pytorch-cpu"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true